version: '3.1'

services:
  pg:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123qweASD"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_backup:/var/lib/postgresql/backup
    restart: always